const test = require('node:test');
const assert = require('node:assert/strict');
const mongoose = require('mongoose');
const Event = require('../models/Events');
const User = require('../models/User');
const Notification = require('../models/Notifications');
const c = require('../controllers/event.controller');
const { promoteWaitlist } = require('../services/waitlist');
const reply = () => ({ code: 200, status(code) { this.code = code; return this; }, json(body) { this.body = body; return this; }, send(body) { this.body = body; return this; } });
const invoke = async (handler, id, userId, body = {}, params = {}) => {
  const res = reply();
  await handler({ params: { id: String(id), ...params }, user: { id: String(userId) }, body }, res);
  assert.ok(res.code < 400, JSON.stringify(res.body));
  return res;
};
test('FIFO promotion, withdrawals, capacity changes and concurrent registration', { skip: !process.env.TEST_MONGO_URI }, async () => {
  await mongoose.connect(process.env.TEST_MONGO_URI, { dbName: `unieventia_waitlist_test_${process.pid}`, serverSelectionTimeoutMS: 5000 });
  try {
    const users = await User.create(Array.from({ length: 14 }, (_, i) => ({ fname: 'Test', lname: 'User', username: `waitlist${i}`, email: `waitlist${i}@example.com`, password: 'test-hash', role: i === 0 ? 'Organizer' : 'Participant' })));
    const [owner, a, b, first, second, leave, last] = users;
    const data = { title: 'Workshop', description: 'Details', location: 'Hall', startDate: new Date(Date.now() + 86400000), endDate: new Date(Date.now() + 90000000), maxParticipants: 2 };
    const event = await Event.create({ ...data, organizer: owner._id });
    for (const user of [a, b, first, second]) await invoke(c.participateEvent, event._id, user._id);
    let stored = await Event.findById(event._id);
    assert.deepEqual(stored.waitlist.map(String), [String(first._id), String(second._id)]);
    const repeat = await invoke(c.participateEvent, event._id, first._id);
    assert.equal(repeat.body.status, 'waitlisted');
    assert.equal(repeat.body.position, 1);
    await invoke(c.cancelParticipation, event._id, a._id);
    stored = await Event.findById(event._id);
    assert.ok(stored.participants.some(id => id.equals(first._id)));
    assert.equal(await Notification.countDocuments({ recipient: first._id, event: event._id }), 1);
    await invoke(c.removeParticipant, event._id, owner._id, {}, { participantId: String(b._id) });
    assert.ok((await Event.findById(event._id)).participants.some(id => id.equals(second._id)));
    for (const user of [leave, last]) await invoke(c.participateEvent, event._id, user._id);
    await invoke(c.leaveWaitlist, event._id, leave._id);
    await invoke(c.updateEvent, event._id, owner._id, { ...data, maxParticipants: 3, language: 'English', wheelchairAccess: 'partial', cost: 'Free', transport: 'Bus 10', whatToBring: 'Laptop' });
    stored = await Event.findById(event._id);
    assert.equal(stored.participants.length, 3);
    assert.equal(stored.waitlist.length, 0);
    assert.equal(stored.whatToBring, 'Laptop');
    await invoke(c.updateEvent, event._id, owner._id, { ...data, maxParticipants: 3 });
    assert.equal((await Event.findById(event._id)).language, 'English');
    const denied = reply();
    await c.updateEvent({ params: { id: String(event._id) }, user: { id: String(owner._id) }, body: { ...data, maxParticipants: 1 } }, denied);
    assert.equal(denied.code, 400);
    const deniedOwner = reply();
    await c.participateEvent({ params: { id: String(event._id) }, user: { id: String(owner._id) }, body: {} }, deniedOwner);
    assert.equal(deniedOwner.code, 403);
    const legacy = await Event.create({ ...data, organizer: owner._id });
    await Event.collection.updateOne({ _id: legacy._id }, { $unset: { waitlist: '', maxParticipants: '' } });
    await invoke(c.participateEvent, legacy._id, a._id);
    assert.equal((await Event.findById(legacy._id)).participants.length, 1);
    const race = await Event.create({ ...data, organizer: owner._id });
    await Promise.all(users.slice(1).map(user => invoke(c.participateEvent, race._id, user._id)));
    stored = await Event.findById(race._id);
    assert.equal(stored.participants.length, 2);
    assert.equal(stored.waitlist.length, 11);
    assert.equal(new Set([...stored.participants, ...stored.waitlist].map(String)).size, 13);
    const expected = stored.waitlist.slice(0, 2).map(String);
    await Promise.all(stored.participants.map(id => invoke(c.cancelParticipation, race._id, id)));
    stored = await Event.findById(race._id);
    assert.deepEqual(stored.participants.map(String), expected);
    assert.equal(stored.waitlist.length, 9);
    const stopped = await Event.create({ ...data, organizer: owner._id, maxParticipants: 1, waitlist: [a._id], startDate: new Date(Date.now() - 1000) });
    await promoteWaitlist(stopped._id);
    assert.equal((await Event.findById(stopped._id)).participants.length, 0);
  } finally { await mongoose.connection.dropDatabase(); await mongoose.disconnect(); }
});
